import { Cairo } from "next/font/google";

import "./globals.css";
import Header from "./components/Header";
import Loading from "./components/Loading ";
const inter = Cairo({ subsets: ["latin"] });
import 'line-awesome/dist/line-awesome/css/line-awesome.min.css';
import Sw from "./sw";
import useOneSignal from './hooks/useOneSignal';
import SubscribeButton from "./components/SubscribeButton";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


  export default function RootLayout({ children, loading }) {

  return (
    <html lang="en" data-theme="fantasy" dir="rtl">
      <head>
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#FFFFFF" />

          <script rel="OneSignal" href="/OneSignalSDKWorker.js" ></script>
          </head>
      <body className={inter.className}>
        <Sw />

        {loading ? <Loading /> : children}
        <div className="w-full h-20 bg-white"></div>

        <Header />
      </body>
    </html>
  );
}
